# Generated by Django 6.0.4 on 2026-05-21 22:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('uso', 'Uso da Tag'), ('cobranca', 'Cobrança'), ('cancelamento', 'Cancelamento'), ('impacto', 'Impacto Ambiental'), ('calculadora', 'Calculadora'), ('geral', 'Geral')], default='geral', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('pessoa', 'Pessoa Física'), ('empresa', 'Empresa')], default='pessoa', max_length=10)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_passages', models.IntegerField(default=0)),
                ('total_co2_saved', models.FloatField(default=0.0)),
                ('total_time_saved', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('category', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('caminhao', 'Caminhão')], default='carro', max_length=10)),
                ('fuel', models.CharField(choices=[('combustao', 'Combustão'), ('eletrico', 'Elétrico'), ('hibrido', 'Híbrido')], default='combustao', max_length=10)),
                ('plate', models.CharField(blank=True, max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('total_passages', models.IntegerField(default=0)),
                ('total_co2_saved', models.FloatField(default=0.0)),
                ('total_time_saved', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('pedagio', 'Pedágio'), ('estacionamento', 'Estacionamento'), ('acesso', 'Controle de Acesso')], default='pedagio', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('co2_saved', models.FloatField(default=0.0)),
                ('time_saved', models.FloatField(default=0.0)),
                ('fuel_saved', models.FloatField(default=0.0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle')),
            ],
            options={
                'verbose_name': 'Passagem',
                'verbose_name_plural': 'Passagens',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_passages', models.IntegerField(default=0)),
                ('total_co2_saved', models.FloatField(default=0.0)),
                ('total_time_saved', models.FloatField(default=0.0)),
                ('total_fuel_saved', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estatística Mensal',
                'verbose_name_plural': 'Estatísticas Mensais',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
