# Generated by Django 6.0.4 on 2026-06-02 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do veículo')),
                ('tipo', models.CharField(choices=[('carro_combustao', 'Carro (Combustão)'), ('carro_eletrico', 'Carro (Elétrico)'), ('moto', 'Moto'), ('caminhao', 'Caminhão')], max_length=20)),
                ('placa', models.CharField(blank=True, max_length=10, verbose_name='Placa')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Passagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.CharField(choices=[('pedagio', 'Pedágio'), ('estacionamento', 'Estacionamento'), ('acesso_controlado', 'Acesso Controlado')], max_length=20)),
                ('data', models.DateField(verbose_name='Data')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Passagens')),
                ('co2e_por_passagem', models.DecimalField(decimal_places=6, default=0, help_text='Calculado automaticamente no momento do registro.', max_digits=10, verbose_name='CO₂e por passagem (kg)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passagens_na_empresa', to=settings.AUTH_USER_MODEL, verbose_name='Empresa / Local')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passagens', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passagens', to='home.veiculo')),
            ],
            options={
                'verbose_name': 'Passagem',
                'verbose_name_plural': 'Passagens',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='VeiculoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos_clientes', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_cadastradas', to='home.veiculo')),
            ],
            options={
                'verbose_name': 'Vínculo Veículo-Empresa',
                'verbose_name_plural': 'Vínculos Veículo-Empresa',
                'unique_together': {('veiculo', 'empresa')},
            },
        ),
    ]
